# skin dataset for MERGE

load_image: &LOAD
  CropPatchFromImageD:
    image_key: 'image'
    patch_key: 'image'
    x_key: 'tissue_x_coords'
    y_key: 'tissue_y_coords'
    patch_size: 256
  ToTensorD:
    keys: ['counts', 'image']
  EnsureChannelFirstD:
    keys: ['image']
    channel_dim: -1
  CenterSpatialCropD:
    keys: ['image']
    roi_size: [224, 224]


normalize: &NORM
  ScaleIntensityD:
    keys: ['image']
    minv: 0.0
    maxv: 1.0

name: 'skin_stage1'
dataset:
  data_dir: '${oc.env:DATASET_LOCATION, ./data}/MERGE_data/skin'
  primary_key: 'image'
  parser:
    image: "lambda x: x.endswith('.svs')"
    spot_num: "lambda x: len(pd.read_csv(x.replace('/svs', '/barcodes').replace('.svs', '.csv'), header=None)[0].values)"
    tissue_positions: "lambda x: (y := pd.read_csv(x.replace('/svs', '/tissue_positions').replace('.svs', '.csv'), index_col=0), y[y['in_tissue'] == 1])[1]"
    tissue_x_coords: ['tissue_positions', "lambda x: x['pxl_col_in_fullres'].values.astype(float)"]
    tissue_y_coords: ['tissue_positions', "lambda x: x['pxl_row_in_fullres'].values.astype(float)"]
    temp_count: "lambda x: np.load(x.replace('/svs', '/counts_spcs_to_8n').replace('.svs', '.npy'))"
    counts: ['temp_count', "lambda x: x.tolist()"]
    nonzero_indices: ['temp_count', "lambda x: x.sum(axis=1) > 0"]
  n_folds: 8
  fold: 0
  test_split_ratio: 0.15
  split_save_dir: "./exp/${dataset_folder.name}-${dataset_folder.dataset.n_folds}folds-seed${dataset_folder.dataset.seed}/split${dataset_folder.dataset.test_split_ratio}"
  group_by:
  explode: ['tissue_x_coords', 'tissue_y_coords', 'counts', "nonzero_indices"]
  drop: ['tissue_positions', 'temp_count']
  split_cols: ['image']
  shuffle: True
  seed: 3927
  use_existing_split: False
  reset_split_index: True
  dataset: 'Dataset'  # class
  dataset_params:
  transform:
    <<: *LOAD
    <<: *NORM
mixup:
#  mixup_ratio: 25
#  mixup_keys: ['image', 'label']
dataloader:
  train_loader:
    shuffle: True
    batch_size: 8
    num_workers: 6
    pin_memory: true
    persistent_workers: true
  val_loader:
    shuffle: False
    num_workers: 6
    batch_size: 8
  test_loader:
    shuffle: False
    num_workers: 6
    batch_size: 8