# DISCOVER model using HCC-WCH dataset

callbacks:  # inline definition of callbacks, don't change the name
  # relevant input arguments in main.py
  ModelCheckpoint:
    filename: "model_{epoch:02d}_{val_loss:.4f}"
    monitor: "val_loss"  # log in module/example_module.py
    save_top_k: 5
    mode: "min"
    save_last: True
  EarlyStopping:
    monitor: 'val_loss'
    patience: 8
    mode: 'min'
    check_on_train_epoch_end: False
  TQDMProgressBar:
    refresh_rate: 1
  LearningRateLogger:
trainer:  # inline definition of trainer, don't change the name
  max_epochs: 2
  accelerator: 'gpu'
  devices: 1
  check_val_every_n_epoch: 2
  log_every_n_steps: 2
# module settings: used in module/example_module.py
criterion:
  criterion: 'FocalLoss'
  criterion_params:
    gamma: 2.0
    alpha: 0.25
    reduction: 'mean'
optimizer:
  optimizer: Adam
  optimizer_params:
    lr: 1e-5
    betas: [0.9, 0.999]
model:
  model: 'VGG19Binary'
  model_params:
    dropout: 0.5
    num_classes: 2