# DISCOVER model using HCC-WCH dataset

callbacks:  # inline definition of callbacks, don't change the name
  # relevant input arguments in main.py
  ModelCheckpoint:
    filename: "model_{epoch:02d}_{val_loss:.4f}"
    monitor: "val_loss"  # log in module/example_module.py
    save_top_k: 5
    mode: "min"
    save_last: True
  EarlyStopping:
    monitor: 'val_loss'
    patience: 8
    mode: 'min'
    check_on_train_epoch_end: False
  TQDMProgressBar:
    refresh_rate: 1
  LearningRateLogger:
trainer:  # inline definition of trainer, don't change the name
  max_epochs: 2
  accelerator: 'gpu'
  devices: 1
  check_val_every_n_epoch: 2
  log_every_n_steps: 2
# module settings: used in module/train_module.py
model:
  model: 'ExplainModel'
  model_params:
    img_ch: 3
    num_classes: '${num_classes}'
    latent_dim: 350
    disc_hidden_dim: 2048
    subset_dim: 14
    stddev: 0.03
    leaky_relu_slope: 0.2
    dropout_rate: 0.5
criterion:
  criterion: 'TotalLoss'
  criterion_params:
    ch: 3
    num_classes: '${num_classes}'
    clf_path: /media/lai/cbe9a31e-b62c-4de2-b86d-3d6ea08c8013/Ross/exp_results/DISCOVER/2025-09-20_14-51-49_job/lightning_logs/version_0/checkpoints/last.ckpt
    vgg_layers: ['3', '8', '13', '18', '23', '28', '33']
    cov_k: 10
    cov_eps: 1e-4
    dropout: 0.5
    loss_weights: [1, 1, 1, 1, 1, 1, 1, 1, 1]
optimizer:
  optimizer: Adam
  optimizer_params:
    lr: 1e-5
    betas: [0.9, 0.999]
extra:
  latent_dim: '${model_folder.model.model_params.latent_dim}'